### ISSUE TITLE
iOS 15 can not play music in the background

### ISSUE THREAD

**Issue by DkSuperMan** [jorgenhenrichsen/SwiftAudio#142]
This seems to be caused by using avplayer,  stop the music after it’s finished playing. should we use avaudioplayer?

**Comment by dcvz** [comment]
@DkSuperMan are you switching tracks from the notification center?

**Comment by efguydan** [comment]
When you play a lot of tracks using QueuedAudioPlayer. When the first track finishes playing, it stops instead of playing the next track.

**Comment by novecapa** [comment]
Can you try with the other fork?

pod 'SwiftAudioEx', :git => 'https://github.com/DoubleSymmetry/SwiftAudioEx.git', :tag => '0.14.4'

**Comment by DkSuperMan** [comment]
The cause of the problem I have found is due to its internal multiple calls to enableRemoteCommands. At present, I feel that this project is not under maintenance. I hope my findings can help you.

**Comment by dcvz** [comment]
@DkSuperMan the bug with the multiple remote commands has been fixed at the fork linked above to you. This is also the same fork linked in the README of this repository.

**Comment by JhonnyTawk** [comment]
@dcvz Not solved I tried the new changes, Play a song -> go to background -> wait till the next song -> nothing happens and the player is paused
